project_name: "{{`{{ .ProjectName }}`}}"

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: "./cmd/test-api"
    ldflags:
      - -s -w
      - -X main.Version={{`{{.Version}}`}}
      - -X main.CommitSHA={{`{{.Commit}}`}}
      - -X main.BuildDate={{`{{.Date}}`}}
    binary: "test-api"

archives:
  - format: tar.gz
    name_template: "test-api_{{.Version}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      # LICENSE file is optional but recommended
      # - LICENSE
      # Documentation directory is optional
      # - docs/*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{`{{ incpatch .Version }}`}}-next"

# SBOM désactivé temporairement pour éviter les erreurs
# sboms:
#   - id: "test-api-sbom"
#     artifacts: binary
#     documents:
#       - "test-api_{{.Version}}_{{.Os}}_{{.Arch}}_sbom.spdx.json"
