archives:
    - format: tar.gz
      format_overrides:
        - format: zip
          goos: windows
      name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
before:
    hooks:
        - go mod tidy
builds:
    - binary: server
      env:
        - CGO_ENABLED=0
      goarch:
        - amd64
        - arm64
        - arm
      goos:
        - linux
        - darwin
        - windows
        - freebsd
      ignore:
        - goarch: arm
          goos: windows
      main: ./cmd/server
checksum:
    name_template: checksums.txt
sboms:
    - artifacts: archive
version: 2
