project_name: test-api

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

    # Configuration for an application
    # Find the main entry point by priority order
    
    main: ./cmd/test-api   # Use the specified path if available
    
    ldflags:
      - -s -w
      - -X main.Version={{`{{.Version}}`}}
      - -X main.CommitSHA={{`{{.Commit}}`}}
      - -X main.BuildDate={{`{{.Date}}`}}
    binary: test-api


archives:
  - format: tar.gz
    name_template: "test-api_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      # LICENSE file is optional but recommended
      # - LICENSE
      # Documentation directory is optional
      # - docs/*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Generate Software Bill of Materials (SBOM) for all binaries
sboms:
  - id: test-api-sbom
    artifacts: archive
    documents:
      - "test-api_{{ .Version }}_{{ .Os }}_{{ .Arch }}_sbom.spdx.json"
    cmd: syft

snapshot:
  name_template: "{{ incpatch .Version }}-next"

