version: '3'

vars:
  BINARY_NAME: test-api
  VERSION:
    sh: git describe --tags --always --dirty
  COMMIT:
    sh: git rev-parse --short HEAD
  DATE:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  BUILD_DIR: dist
  BUILD_FLAGS: -ldflags "-s -w -X main.Version={{.VERSION}} -X main.CommitSHA={{.COMMIT}} -X main.BuildDate={{.DATE}}"
  MAIN_PACKAGE: ./cmd/test-api

tasks:
  build:
    desc: Build for the current platform
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build {{.BUILD_FLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PACKAGE}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - |
        if ! command -v golangci-lint &> /dev/null; then
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        fi
      - golangci-lint run

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - mkdir -p {{.BUILD_DIR}}

  release-local:
    desc: Build a release binary for your current OS only
    cmds:
      - task: build
      - echo "Binary built for {{OS}}/{{ARCH}} -> {{.BUILD_DIR}}/{{.BINARY_NAME}}"
    silent: false

  build-linux-amd64:
    desc: Build for linux/amd64
    cmds:
      - go build {{.BUILD_FLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-linux-amd64 {{.MAIN_PACKAGE}}
    env:
      GOOS: linux
      GOARCH: amd64
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}-linux-amd64"

  build-darwin-amd64:
    desc: Build for darwin/amd64
    cmds:
      - go build {{.BUILD_FLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-amd64 {{.MAIN_PACKAGE}}
    env:
      GOOS: darwin
      GOARCH: amd64
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-amd64"

  release:
    desc: Build release binaries for all supported platforms
    deps: 
      - clean
      - test
      - build-linux-amd64
      - build-darwin-amd64
    cmds:
      - echo "Release binaries created in {{.BUILD_DIR}}/"
    silent: false
